### PR TITLE
Fix for #30

### PR DESCRIPTION
**Pull request by MatrixCrawler**
Fix for Issue #30 

* added check for plesk port
* added test-cases
* added test config files

Could not test it on live plesk yet. had to rely on unit-tests

### CODE REVIEW

**Comment by Heidschnucke** [comment]
Thank you for your great effort!

I have tested your branch on live plesk. I get the same error (agent.php 404, although it is avaiable under https://medicusto.de:8881/enterprise/control/agent.php)

**Comment by xgin** [comment]
I think this is quite risky approach of port detection: any config changes could break it. e.g. I'm not sure about enabling of http2
The high risk is mostly because your code works for even the default configuration with 8443 port.
And forward-looking it blocks connection to Plesk in docker and any thoughts about Windows.

What do you think about the following solution #38?
The option could be either set in config or passed from Plesk extension.

**Comment by xgin** [comment]
I'm going to merge this PR with some additional fixes a bit later.

**Comment by xgin** [comment]
Close in favour of #50

**Pull request closed without merging**
